# Generated by Django 4.1.7 on 2023-03-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority', '-updated')},
        ),
    ]
