# Generated by Django 4.1.7 on 2023-03-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('board', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.board')),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
